language: android
sudo: false
jdk: 
  - oraclejdk8

env:
  matrix:
    - ANDROID_TARGET=android-19 ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support
    - extra
    - addon
    - sys-img-armeabi-v7a-android-19

cache:
  directories:
    # gradle version from gradle-wrapper.properties
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep build/outputs | tr "\n" ":")

before_script:
  - echo no | android create avd --force --name test --target android-19 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew check -PdisablePreDex --continue --stacktrace
   - ./gradlew connectedAndroidTest -PdisablePreDex --continue --stacktrace

after_failure:
  - pandoc $TRAVIS_BUILD_DIR/sidekick-sample/build/reports/tests/release/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  - pandoc $TRAVIS_BUILD_DIR/sidekick-sample/build/reports/androidTests/connected/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

after_script:
  - for f in $TRAVIS_BUILD_DIR/sidekick/build/outputs/lint-results.html; do pandoc $f -t plain; done
  - for f in $TRAVIS_BUILD_DIR/sidekick-sample/build/outputs/lint-results.html; do pandoc $f -t plain; done
