language: android

sudo: false

jdk: 
  - oraclejdk8

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-24.0.3
    - android-24
    - extra-android-m2repository
    - extra-android-support

cache:
  directories:
    # gradle version from gradle-wrapper.properties
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

script:
   - ./gradlew clean assembleDebug test lint

after_script:
  - cat /home/travis/build/felixWackernagel/sidekick/sidekick/build/lint-report.html
  - cat /home/travis/build/felixWackernagel/sidekick/sidekick-sample/build/lint-report.html
  - echo $TRAVIS_BUILD_DIR
