package de.wackernagel.android.sidekick;

import com.google.auto.service.AutoService;
import com.squareup.javapoet.ClassName;
import com.squareup.javapoet.FieldSpec;
import com.squareup.javapoet.JavaFile;
import com.squareup.javapoet.TypeSpec;

import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.Modifier;
import javax.lang.model.element.TypeElement;
import javax.tools.Diagnostic;

import de.wackernagel.android.sidekick.annotations.Contract;

import static com.squareup.javapoet.TypeSpec.classBuilder;
import static javax.lang.model.element.Modifier.FINAL;
import static javax.lang.model.element.Modifier.PUBLIC;

@AutoService(Processor.class)
public class ContractProcessor extends AbstractProcessor {

    @Override
    public Set<String> getSupportedAnnotationTypes() {
        return Collections.singleton(Contract.class.getCanonicalName());
    }

    @Override
    public SourceVersion getSupportedSourceVersion() {
        return SourceVersion.latestSupported();
    }

    @Override
    public boolean process(Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (Element annotatedElement : roundEnv.getElementsAnnotatedWith(Contract.class)) {
            final TypeElement annotatedClass = (TypeElement) annotatedElement;
            final String authority = annotatedClass.getAnnotation(Contract.class).authority();
            final String className = annotatedClass.getSimpleName().toString();
            final String packageName = JavaUtils.getPackageName(processingEnv.getElementUtils(), annotatedClass);
            if (packageName == null) {
                processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "No package for " + className + ". SKIP");
                continue;
            }

            final Set<Element> methods = JavaUtils.getAbstractMethods(annotatedClass);
            final Set<String> columnConstants = getColumns( methods );
            final TypeSpec generatedClass = generateContract(className, columnConstants, methods, authority);
            writeClass(generatedClass, packageName, className);
        }
        return true;
    }

    private Set<String> getColumns(Set<Element> methods) {
        final Set<String> columns = new HashSet<>( methods.size() );
        columns.add("COLUMN_ID");
        for( Element method : methods ) {
           columns.add("COLUMN_" + columnName(method.getSimpleName().toString()).toUpperCase());
        }
        return columns;
    }

    private void writeClass(final TypeSpec generatedClass, final String packageName, final String className) {
        processingEnv.getMessager().printMessage(Diagnostic.Kind.NOTE, "Generate contract for " + packageName + "." + className);
        try {
            JavaFile javaFile = JavaFile.builder(packageName, generatedClass).build();
            javaFile.writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            processingEnv.getMessager().printMessage(Diagnostic.Kind.WARNING, "File wasn't generated.");
        }
    }

    private static TypeSpec generateContract(final String className, final Set<String> columns, final Set<Element> methods, final String authority) {
        final TypeSpec.Builder classBuilder = classBuilder(className + "Contract")
                .addModifiers(PUBLIC, FINAL)
                .addJavadoc("Generated by Sidekick at " + new SimpleDateFormat("dd.MM.yyyy HH:mm", Locale.ENGLISH).format(new Date()) + "\n")
                .addField(constant(String.class, "TABLE", tableName(className) ) );
        columnConstants( classBuilder, columns );
        projection( classBuilder, columns, methods );
        contentUri(classBuilder, authority);
        return classBuilder.build();
    }

    private static void columnConstants( final TypeSpec.Builder classBuilder, final Set<String> columns ) {
        for( String columnConstant : columns ) {
            String value = columnConstant.substring( "COLUMN_".length() ).toLowerCase();
            if( value.equals( "id" ) ) {
                value = "_".concat( value );
            }
            classBuilder.addField(
                    constant( String.class, columnConstant, value ) );
        }
    }

    private static void projection( final TypeSpec.Builder classBuilder, final Set<String> columns, final Set<Element> methods ) {
        if( methods.size() > 0 ) {
            final StringBuilder pattern = new StringBuilder();
            pattern.append( "$L" );

            for( Element method : methods ) {
                if( pattern.length() > 0 ) {
                    pattern.append(", ");
                }
                pattern.append("$L");
            }

            classBuilder.addField(
                FieldSpec.builder( String[].class, "PROJECTION" )
                        .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                        .initializer("{ " + pattern.toString() + " }", columns.toArray() )
                        .build());
        }
    }

    private static void contentUri(final TypeSpec.Builder classBuilder, final String authority) {
        if (authority != null && authority.length() > 0) {
            ClassName uri = ClassName.get( "android.net", "Uri" );
            classBuilder.addField(
                FieldSpec.builder( uri, "CONTENT_URI")
                    .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                    .initializer("Uri.parse( \"content://" + authority + "/\" + $L )", "TABLE")
                    .build());
        }
    }

    private static String columnName(final String methodName) {
        String name = methodName;
        if (name.startsWith("get")) {
            name = methodName.substring(3);
        }

        final StringBuilder sb = new StringBuilder(name);
        final int length = sb.length();
        int offset = 0;
        for (int index = 0; index < length; index++) {
            if (index > 0 && Character.isUpperCase(name.charAt(index))) {
                sb.insert(index + offset, "_");
                offset++;
            }
        }
        return sb.toString().toLowerCase();
    }

    private static String tableName(final String className) {
        final String name = className.toLowerCase();
        if (name.endsWith("s"))
            return name;
        return name + "s";
    }

    private static FieldSpec constant(final Class<?> type, final String name, final String value) {
        return constant(type, name, "$S", value);
    }

    private static FieldSpec constant(final Class<?> type, final String name, final String pattern, final String value) {
        return FieldSpec.builder(type, name)
                .addModifiers(Modifier.PUBLIC, Modifier.STATIC, Modifier.FINAL)
                .initializer(pattern, value)
                .build();
    }

}
